// Embeds src/selector.ts into js/snippet.js so the Code tab works without fetch (also from file://).
// Run: node tools/build-snippet.js
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = fs.readFileSync(path.join(root, 'src', 'selector.ts'), 'utf8');
const out = '/* Generated by tools/build-snippet.js from src/selector.ts — do not edit by hand. */\n' +
  'window.TurkicSnippet = ' + JSON.stringify(src) + ';\n';
fs.writeFileSync(path.join(root, 'js', 'snippet.js'), out);
console.log('js/snippet.js written (' + src.length + ' chars)');
